# Generated by Django 5.2.13 on 2026-09-06 22:55

import django.core.validators
import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Cybersecurity Engineer / Developer', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. CYBERSECURITY • SOFTWARE ENGINEERING • OFFENSIVE SECURITY', max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('resume_file', models.FileField(blank=True, help_text='Upload resume (PDF, DOC, DOCX)', null=True, upload_to=portfolio.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='JSON array of focus areas, e.g. ["Offensive Security", "Web Security"]')),
                ('currently_doing', models.JSONField(blank=True, default=list, help_text='JSON array of current activities, e.g. ["Building", "Learning"]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or thumbnail', null=True, upload_to=portfolio.models.project_image_path)),
                ('technologies', models.JSONField(default=list, help_text='JSON array of technology names, e.g. ["Django", "React", "PostgreSQL"]')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('security_category', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Key feature highlights')),
                ('challenges', models.TextField(blank=True)),
                ('architecture', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio Terminal', max_length=200)),
                ('terminal_welcome', models.TextField(blank=True, help_text='Custom terminal welcome/boot message')),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('email', 'Email'), ('hackthebox', 'HackTheBox'), ('tryhackme', 'TryHackMe'), ('website', 'Website'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(blank=True, help_text='Display label override', max_length=100)),
                ('url', models.CharField(help_text='URL or email address', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
