# Generated by Django 5.2.13 on 2026-09-06 23:57

import django.core.validators
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of certifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of education records'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_security',
            field=models.FileField(blank=True, help_text='Upload Cybersecurity Resume', null=True, upload_to=portfolio.models.resume_security_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_software',
            field=models.FileField(blank=True, help_text='Upload Software Engineering Resume', null=True, upload_to=portfolio.models.resume_software_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteering',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of volunteering activities'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='is_github_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('security', 'Security / Pentesting'), ('software', 'Software Engineering'), ('fullstack', 'Full Stack'), ('research', 'Research & Exploitation'), ('lab', 'Lab / Virtual Environment'), ('other', 'Other')], default='security', help_text='Classification track for portfolio filtering', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, help_text='GitHub repository name (e.g. hardikgaikwad/PrivShare)', max_length=150),
        ),
    ]
