# Generated by Django 5.2.13 on 2026-09-07 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_certifications_profile_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. eJPT', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='e.g. INE Security', max_length=200)),
                ('status', models.CharField(blank=True, help_text='e.g. Certified, Global Top 4%', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed text shown in terminal (completed paths, skills, etc.)')),
                ('url', models.URLField(blank=True, help_text='Optional verification or profile URL')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text='e.g. B.Tech — Information Technology', max_length=200)),
                ('period', models.CharField(help_text='e.g. 2023–2027', max_length=100)),
                ('grade', models.CharField(blank=True, help_text='e.g. CGPA: 7.69/10 or Class XII: 90.8%', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='about_terminal_content',
            field=models.TextField(blank=True, help_text='Content shown by "cat about.txt" in the terminal. Editable from Admin.'),
        ),
        migrations.AddField(
            model_name='project',
            name='terminal_content',
            field=models.TextField(blank=True, help_text='Full text content shown by "cat projects/<filename>" in the terminal. If blank, auto-generated from project fields.'),
        ),
        migrations.AddField(
            model_name='project',
            name='terminal_filename',
            field=models.CharField(blank=True, help_text='Virtual filename in terminal ~/projects/ (e.g. privshare.txt). Auto-generated from slug if left blank.', max_length=100, validators=[django.core.validators.RegexValidator(message='Filename must end with .txt, contain only letters, digits, dots, hyphens, underscores, and not start with a dot or dash.', regex='^[a-zA-Z0-9][a-zA-Z0-9._-]*\\.txt$')]),
        ),
    ]
