# Generated by Django 5.2.13 on 2026-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_seed_terminal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Filter name, e.g. 'Security', 'Software Development'", max_length=100)),
                ('slug', models.SlugField(help_text="Slug identifier, e.g. 'security', 'software-development'", max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which filter appears in the UI')),
                ('is_active', models.BooleanField(default=True, help_text='Whether filter is visible in the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Filter / Category',
                'verbose_name_plural': 'Project Filters / Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_security_url',
            field=models.CharField(blank=True, default='/resumes/cybersecurity.pdf', help_text='Direct accessible URL for Cybersecurity resume. Can be a local path (/resumes/cybersecurity.pdf) or external URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_software_url',
            field=models.CharField(blank=True, default='/resumes/software-development.pdf', help_text='Direct accessible URL for Software Development resume. Can be a local path (/resumes/software-development.pdf) or external URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Dynamic categories / filters associated with this project', related_name='projects', to='portfolio.projectcategory'),
        ),
    ]
